### ISSUE TITLE
Running Guided Configuration Can't Find Autopilot?

### ISSUE THREAD

**Issue by jmdelahanty** [auto-pi-lot/autopilot#193]
I'm running into an issue getting autopilot configured on my own pi unfortunately! 

When I type

`python -m autopliot.setup`

I get this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/jdelahanty/autopilot/autopilot/__init__.py", line 14, in <module>
    __version__ = version("auto-pi-lot")
  File "/usr/lib/python3.9/importlib/metadata.py", line 551, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: auto-pi-lot
```

As far as I can tell, I'm in my auto-pi-lot poetry environment, here's what my command line looks like:

`(auto-pi-lot-py3.9) jdelahanty@trixie1:~/autopilot $`

Any advice?

**Comment by jmdelahanty** [comment]
This has suddenly stopped happening which is nice! Now fails at installing scipy, I think because it's so damn slow to download on the bad internet I have at the house I rent in. It takes forever to download most things and it fails with messages like:

```
ReadTimeoutError

HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

```

Not sure how to get around that lol. Might just move the pi downstairs so it's closer to the wifi since I can ssh to it!

**Comment by jmdelahanty** [comment]
Looks like it eventually worked, not sure what happened to fix it! But hooray, it's running on my home pi.
